version: 2.1

jobs:
  test:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: System Setup
          command: |
            sudo apt-get -qq update -y
            sudo apt-get -q install -y software-properties-common curl ca-certificates wget make 
            sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt-get -qq update -y
            sudo apt-get -q install -y python3.6
            python ––version
      - run:
          name: Docker up
          command: |
            docker-compose up -d
      - run:
          name: Run capture
          command: |
            virtualenv -p python3.6 venv
            source venv/bin/activate
            pip3 install -r app/requirements.txt
            python3 app/capture.py

workflows:
  version: 2
  build_and_package:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
