version: 2.1

jobs:
  test:
    machine:
      enabled: true
      image: ubuntu-1804
    steps:
      - checkout
      - run:
          name: System Setup
          command: |
            sudo apt-get -qq update -y
            sudo apt-get -q install -y curl ca-certificates wget make
            (cd ..; git clone https://github.com/antirez/redis.git; cd redis; git checkout 5.0.8; make -j$(nproc); sudo make install)
      - run:
          name: Docker up
          command: |
            docker-compose up

workflows:
  version: 2
  build_and_package:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
